# Site settings
baseurl = "https://calebabg.github.io/"
languageCode = "en-us"
title = "CalebABG Photography"
theme = "photo-grid"

[params]
    # Meta
    no_exif = true
    title = "Photography Portfolio"
    subtitle = "This is a collection of some of my photography, please enjoy! Click on an image for more info! -- I made this static site with GoLang [Hugo](https://github.com/gohugoio/hugo), using the theme: [Photo-Grid](https://github.com/Chen-Zhe/photo-grid)"
    author = "Caleb A. Bostic-Gardner"
    description = "A home for my photograpy"
    keywords = "Hugo, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "All images © 2020 Caleb A. Bostic-Gardner"
